### ISSUE TITLE
WLO 1.0.1 release

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#209]
Remember to use the 1.0.x branch for the release and not the main branch

- [x] Verify the upgrade support (use the catalog image produced by 1P)
- [x] Scans(Done for each release build): 
  - [x] VA
  - [x] Twistlock
  - [x] SonarQube
  - [x] Whitesource
- [x] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [x] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [x] Update websphereliberty-app-crd.yaml if necessary
  - [x] Creating the Pre-Release: 
  - [x] Kick off build using the pre-release tags
  - [x] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Mary (Out of containerized step)
- [x] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [ ] Provide customer installable code to PTC for Open Source Clearance
- [x] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [x] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [x] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [x] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Mary (Out of containerized step)
  - [x] Update webspehreliberty-app-crd.yaml to point to GA release image
- [x] Push the images to the production repo (Mary can help with this)
- [x] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [x] Work with ID to add upgrade instructions (use WebSphere Automation Operator docs)
- [x] SVT Testing Needed: Upgrade Scenarios and  Air gap
- [ ] Publish assessment (CASE will get published when this happens)
