### ISSUE TITLE
WLO 1.0.2 release

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#253]
- [x] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline) - [issue #254](https://github.com/wasdev/websphere-liberty-operator/issues/254)
- [x] Scans(Done for each release build): 
  - [x] VA
  - [x] Twistlock
  - [x] SonarQube
  - [x] Mend
  - [x] Aquascan
- [x] Linter (update to latest available linter tool version first in OnePipeline)
- [x] Certification Related Work Items
- [x] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [x] Identify SVT Testing that is needed
- [x] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [ ] Update websphereliberty-app-crd.yaml if necessary
  - [ ] Creating the Pre-Release: 
  - [ ] Kick off build using the pre-release tags
  - [ ] Set the flag to run e2e in all modes
  - [ ] Check e2e results
  - [ ] Provide image details to Mary (Out of containerized step)
- [x] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [ ] Provide customer installable code to PTC for Open Source Clearance
- [ ] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [x] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [x] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Mary ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [ ] Update webspehreliberty-app-crd.yaml to point to GA release image
- [x] Push the images to the production repo (Using CD Instructions)
- [x] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [x] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [x] Publish assessment (CASE will get published when this happens)

**Comment by leochr** [comment]
Operator artifacts for WLO 1.0.2 release (from [release build](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/655c557b-8844-4e69-ac21-66b9e735e4ae/build-containerize/run-stage?env_id=ibm:yp:us-south))

```
Saving artifact operator-1.0.2 name=cp.stg.icr.io/cp/websphere-liberty-operator:1.0.2 digest=sha256:3b4582072246071081e615379d16854992456df2972af131a6e30192a82088e0 type=manifest
Saving artifact operator-1.0.2-amd64 name=cp.stg.icr.io/cp/websphere-liberty-operator:1.0.2-amd64 digest=sha256:6454f01ad42cde636394108ed954c5a5784ffc16b363102bb5bc753a40bc0b99 type=image
Saving artifact bundle-1.0.2 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.0.2 digest=sha256:fec734a261d612829ccdbe429bdb859e949d99f3b2f2a9ede3d00f57b60fe6f1
Saving artifact catalog-1.0.2 name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.0.2 digest=sha256:9d3ffce1b61970fd9f81726c703cc6bc48e303ef538be00a5ee1c7c7a806d953
```

Sample app is updated to:
```
icr.io/appcafe/open-liberty/samples/getting-started@sha256:22d8d29128bb497933990f3eaa5735c9ac702e4e93b77e91d7d1f24c46cc060b
```

**Comment by leochr** [comment]
CD build: https://cloud.ibm.com/devops/pipelines/tekton/e77b8f53-3bb3-471f-bea8-8396bfe6b5be/runs/b11d3859-9dec-44ec-89dc-8661135962d0/prod-finish/run-stage?env_id=ibm:yp:us-south
