### ISSUE TITLE
Release WLO 1.2.1

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#503]
- [ ] Schedule any UFOs for new Features
- [x] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline)
- [x] Scans(Done for each release build): 
  - [x] VA
  - [x] Twistlock
  - [ ] SonarQube
  - [x] Mend
  - [x] Aquascan
- [x] Linter
- [x] Certification Related Work Items
- [x] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [x] Identify SVT Testing that is needed
- [x] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [x] Update websphereliberty-app-crd.yaml if necessary
  - [x] Creating the Pre-Release: 
  - [x] Kick off build using the pre-release tags
  - [x] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Mary (Out of containerized step)
- [x] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [x] Provide customer installable code to PTC for Open Source Clearance
- [x] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [x] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [x] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Mary ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [x] Update webspehreliberty-app-crd.yaml to point to GA release image
- [x] Push the images to the production repo (Using CD Instructions)
- [x] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [ ] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [x] Publish assessment (CASE will get published when this happens)
- [ ] Are any patentable ideas delivered with this release?

**Comment by leochr** [comment]
WLO 1.2.1 release builds:
CI: [https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/[…]9f767f7d59/build-containerize/run-stage?env_id=ibm:yp:us-south](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/d3a7735f-dc11-482c-bffa-309f767f7d59/build-containerize/run-stage?env_id=ibm:yp:us-south)
CD: [https://cloud.ibm.com/devops/pipelines/tekton/e77b8f53-3bb3-471f-bea8-8396bfe6b5be/[…]419a-9308-e42a8f4cad5f/prod-start/start?env_id=ibm:yp:us-south](https://cloud.ibm.com/devops/pipelines/tekton/e77b8f53-3bb3-471f-bea8-8396bfe6b5be/runs/629a6d9f-8484-419a-9308-e42a8f4cad5f/prod-start/start?env_id=ibm:yp:us-south)
