### ISSUE TITLE
WLO 1.2.2

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#524]
- [ ] Schedule any UFOs for new Features
- [x] Update operator version
- [x] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline)
- [ ] Scans(Done for each release build): 
  - [ ] VA
  - [x] Twistlock
  - [ ] SonarQube
  - [x] Mend
  - [x] Aquascan
- [ ] Linter
- [ ] Certification Related Work Items
- [x] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [x] Identify SVT Testing that is needed
- [ ] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [ ] Update websphereliberty-app-crd.yaml if necessary
  - [x] Creating the Pre-Release: 
  - [x] Kick off build using the pre-release tags
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Mary (Out of containerized step)
- [x] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [ ] Provide customer installable code to PTC for Open Source Clearance
- [ ] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [x] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [x] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Mary ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [ ] Update webspehreliberty-app-crd.yaml to point to GA release image
- [x] Push the images to the production repo (Using CD Instructions)
- [x] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [x] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [x] Publish assessment (CASE will get published when this happens)
- [ ] Are any patentable ideas delivered with this release?

**Comment by leochr** [comment]
Pre-release driver:
Release (tag): 1.2.2
[WLO CI build #1465](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/68501c1a-3cfd-43c6-9c6c-b787ce1ce6df/build-containerize/run-stage?env_id=ibm:yp:us-south)

Image details:
```
Saving artifact operator-1.2.2 type=manifest [name=cp.stg.icr.io/cp/websphere-liberty-operator:1.2.2](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator:1.2.2) digest=sha256:9b87643c1c1246f5b244c470ef4c4578af664ec5cd432d14be2372fc8289b00d
Saving artifact operator-1.2.2-amd64 type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator:1.2.2-amd64](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator:1.2.2-amd64) digest=sha256:bd873496f5576ad6d531bed32535d649e221ef5cd2009d5771787579eadbd9c6 arch=amd64
Saving artifact operator-1.2.2-ppc64le type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator:1.2.2-ppc64le](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator:1.2.2-ppc64le) digest=sha256:886d3c908bf75e5d4116f5392287ee84032d07eb9bcc75ca76312a9d2c7c5518 arch=ppc64le
Saving artifact operator-1.2.2-s390x type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator:1.2.2-s390x](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator:1.2.2-s390x) digest=sha256:b4ebdf84fa0fe662e7ff4a0221b258744f987f6eb4a93d8b26bb4966b8892871 arch=s390x
Saving artifact bundle-1.2.2 [name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.2.2](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.2.2) digest=sha256:df4e8c18770d107a7a9126fd45e47f5dac2da3d2ffac53357156771e8e19bd0c
Saving artifact catalog-1.2.2 type=manifest [name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.2.2](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.2.2) digest=sha256:b7b3063f93ac3183535ed1a0c63d45042845b9c73d54db063930eeb6a52d6372
Saving artifact catalog-1.2.2-amd64 type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.2.2-amd64](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.2.2-amd64) digest=sha256:69e7f1d95137d5a11cfa72dd9c69b4eb629ecad05e5a20b242edb96f22195541 arch=amd64
Saving artifact catalog-1.2.2-ppc64le type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.2.2-ppc64le](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.2.2-ppc64le) digest=sha256:fda20f28047acc8d576eb12b11fe189aa0393b3f36b3d48b93e8e0110541289a arch=ppc64le
Saving artifact catalog-1.2.2-s390x type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.2.2-s390x](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.2.2-s390x) digest=sha256:ebc8e5ceb27f824f1ba33fbe8efbf79914fde13d6ab87b5d5c3f174a08e8d845 arch=s390x
```

Liberty getting-started sample app was also updated to the following:
```
icr.io/appcafe/open-liberty/samples/getting-started@sha256:6bf52d536e94d6aa6eaa3ca9639e0fe9f5e71dbd891c50362939dd6aca519d02
```
