### ISSUE TITLE
Release WLO 1.3.0

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#578]
- [ ] Schedule any UFOs for new Features
- [ ] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline)
- [ ] Scans(Done for each release build): 
  - [ ] VA
  - [ ] Twistlock
  - [ ] SonarQube
  - [ ] Mend
  - [ ] Aquascan
- [ ] Linter
- [ ] Certification Related Work Items
- [ ] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [ ] Identify SVT Testing that is needed
- [ ] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [ ] Update websphereliberty-app-crd.yaml if necessary
  - [ ] Creating the Pre-Release: 
  - [ ] Kick off build using the pre-release tags
  - [ ] Set the flag to run e2e in all modes
  - [ ] Check e2e results
  - [ ] Provide image details to Mary (Out of containerized step)
- [ ] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [ ] Provide customer installable code to PTC for Open Source Clearance
- [ ] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [ ] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [ ] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [ ] Check e2e results
  - [ ] Provide image details to Mary ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [ ] Update webspehreliberty-app-crd.yaml to point to GA release image
- [ ] Push the images to the production repo (Using CD Instructions)
- [ ] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [ ] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [ ] Publish assessment (CASE will get published when this happens)
- [ ] Are any patentable ideas delivered with this release?

**Comment by leochr** [comment]
Release build: [WLO CI 1707](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/357506ea-fd0b-41c1-902d-9c82b123004a/build-containerize/run-stage?env_id=ibm:yp:us-south)

Sample getting-started image reference: `icr.io/appcafe/open-liberty/samples/getting-started@sha256:b295be1aeefeae9f36b991a70dfd8ef615e3f4a849d6d6091cf51f55221e3c0d`

Image details (tag and SHA) from the build:
```
Saving artifact operator-1.3.0 type=manifest [name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.0](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator:1.3.0) digest=sha256:807bc1d490ff08510873b84529fa766059f5fbc595d2862bd1506c12aa23935c
Saving artifact operator-1.3.0-amd64 type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.0-amd64](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator:1.3.0-amd64) digest=sha256:2a9ad1769d778091e13d0c9b471f2bad836d881a6060359072eab564da2350f6 arch=amd64
Saving artifact operator-1.3.0-ppc64le type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.0-ppc64le](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator:1.3.0-ppc64le) digest=sha256:b90f3792332c91453a1664b4023f4213b2226619882520baeebb661c986a6bb2 arch=ppc64le
Saving artifact operator-1.3.0-s390x type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.0-s390x](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator:1.3.0-s390x) digest=sha256:5f82b31152e793a66b3b56a03a2f77f7f6c7c128456a1ff430212096e0b39970 arch=s390x
Saving artifact bundle-1.3.0 [name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.0](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.0) digest=sha256:eb7689f2bea6d1f642600628ef6eddbbfbe0e85c7979c1a2dfd90a1d9f8b59ce
Saving artifact catalog-1.3.0 type=manifest [name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.0](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.0) digest=sha256:e8fa75a42c5d0ea30f3696ca698d18d9fbd2f866fb50126de23cb5ec0ec662f9
Saving artifact catalog-1.3.0-amd64 type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.0-amd64](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.0-amd64) digest=sha256:4f39bd2ff0646bbf9d84a03efc5b1295b36b228dfcb7df1fe6e514959bf94d3c arch=amd64
Saving artifact catalog-1.3.0-ppc64le type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.0-ppc64le](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.0-ppc64le) digest=sha256:c43d2b73872f82e4aa7851239538b33110c32d0285a325076fa0288f7ed89088 arch=ppc64le
Saving artifact catalog-1.3.0-s390x type=image [name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.0-s390x](http://name%3Dcp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.0-s390x) digest=sha256:613e1780765ddda1272edbffe2c07abc6f565cc513c2d3654af40136a1296136 arch=s390x
CSV FILE: bundle/manifests/ibm-websphere-liberty.clusterserviceversion.yaml
Saving artifact sample-1.3.0 type=image [name=icr.io/appcafe/open-liberty/samples/getting-started](http://name%3Dicr.io/appcafe/open-liberty/samples/getting-started) digest=sha256:474bb2c2ea52419233f7d814156613764b3e7b451f95b669b20acc534b989104 arch=amd64
Saving artifact sample-1.3.0 type=image [name=icr.io/appcafe/open-liberty/samples/getting-started](http://name%3Dicr.io/appcafe/open-liberty/samples/getting-started) digest=sha256:05166c4e1988dc8a90e610d3e441685fcbbc79a45020e1f47d2991ec17f7cb54 arch=ppc64le
Saving artifact sample-1.3.0 type=image [name=icr.io/appcafe/open-liberty/samples/getting-started](http://name%3Dicr.io/appcafe/open-liberty/samples/getting-started) digest=sha256:84f2c27cf9c586f3962ab19170f3ddfa73fe1056e04f25aba1d8bde0fa1580b3 arch=s390x
```

**Comment by leochr** [comment]
@kabicin Please update the CASE with the above image details from the WLO 1.3.0 release build. Thanks

**Comment by leochr** [comment]
Closing as completed
