### ISSUE TITLE
Release WLO 1.3.1

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#605]
- [ ] Schedule any UFOs for new Features
- [x] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline)
- [x] Scans(Done for each release build): 
  - [ ] VA
  - [x] Twistlock
  - [x] SonarQube
  - [x] Mend
  - [x] Aquascan
- [x] Linter
- [ ] Certification Related Work Items
- [x] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [x] Identify SVT Testing that is needed
- [x] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [x] Update websphereliberty-app-crd.yaml if necessary
  - [x] Creating the Pre-Release: 
  - [x] Kick off build using the pre-release tags
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Kirby (Out of containerized step)
- [x] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [ ] Provide customer installable code to PTC for Open Source Clearance
- [x] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [x] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [x] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Kirby ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [ ] Update webspehreliberty-app-crd.yaml to point to GA release image
- [x] Push the images to the production repo (Using CD Instructions)
- [x] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [x] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [x] Publish assessment (CASE will get published when this happens)
- [ ] Are any patentable ideas delivered with this release?

**Comment by leochr** [comment]
@kabicin WLO 1.3.1 pre-release image details. Please update the CASE to produce the tgz file for SVT testing. Thank you.

```
**** Saving Artifacts ****
Saving artifact operator-1.3.1-rc.3 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-rc.3 digest=sha256:f2d0f568b217ab3c8cbc92e7dd9cbcf6f427ec989c2523aa55e58ca3c58ccd18
Saving artifact operator-1.3.1-rc.3-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-rc.3-amd64 digest=sha256:bbc1ff7f2ef8ea8d20f0397662663224026e28e902c3058d383398be252130b1 arch=amd64
Saving artifact operator-1.3.1-rc.3-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-rc.3-ppc64le digest=sha256:1f59004f404af3d9b936ed2c8369797e01f6954625bcf8462f8c7198a3ad5db7 arch=ppc64le
Saving artifact operator-1.3.1-rc.3-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-rc.3-s390x digest=sha256:d584256ab09814c1c662439c2b19381d050413c87b8cff5eb0132823a5b38b5c arch=s390x
Saving artifact bundle-1.3.1-rc.3 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.1-rc.3 digest=sha256:87a5694ef79f8518d09ff972f75bb55ab2596f6e0af2211a9e977835312302fe
Saving artifact catalog-1.3.1-rc.3 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-rc.3 digest=sha256:2aadb6910bc176417b76c62731ede00dbe90f8a99e846345c01dff6af6eb8e39
Saving artifact catalog-1.3.1-rc.3-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-rc.3-amd64 digest=sha256:5e616eae1e6464c1efa9b6e81e91bfa62d533b960f6320692c1ed1d0f91d0a27 arch=amd64
Saving artifact catalog-1.3.1-rc.3-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-rc.3-ppc64le digest=sha256:e8c5456ddf46db7bc325cfbf26a6d9fcc1a0e174350aeac51d0690dcfa880107 arch=ppc64le
Saving artifact catalog-1.3.1-rc.3-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-rc.3-s390x digest=sha256:e96a81c9dd11fbc971e65fbbe9cee28c6de6e9e779a77c0622b9984e637af040 arch=s390x
Saving artifact sample-1.3.1-rc.3 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:474bb2c2ea52419233f7d814156613764b3e7b451f95b669b20acc534b989104 arch=amd64
Saving artifact sample-1.3.1-rc.3 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:05166c4e1988dc8a90e610d3e441685fcbbc79a45020e1f47d2991ec17f7cb54 arch=ppc64le
Saving artifact sample-1.3.1-rc.3 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:84f2c27cf9c586f3962ab19170f3ddfa73fe1056e04f25aba1d8bde0fa1580b3 arch=s390x
```

**Comment by leochr** [comment]
Release CI build: [WLO CI 1819](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/382645cf-fe55-42bc-bbe0-c6593cc14c2b/build-containerize/run-stage?env_id=ibm:yp:us-south)

Release CD build: [WLO CD 76](https://cloud.ibm.com/devops/pipelines/tekton/e77b8f53-3bb3-471f-bea8-8396bfe6b5be/runs/283e38cc-15e6-46f1-92f0-5dbe6d0345b3/prod-start?env_id=ibm:yp:us-south)

IBM Certification PR: https://github.ibm.com/IBMPrivateCloud/charts/pull/22305

---

Image details (tags and SHA):
```
Saving artifact operator-1.3.1 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1 digest=sha256:991cc30ce26c63514e2961e12a476d547cce3a81d8cbfcb14e4b40266aa11234
Saving artifact operator-1.3.1-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-amd64 digest=sha256:3de4683c7b491450cac92cdd8086264809f099bf816fdf49d7ff2467159df804 arch=amd64
Saving artifact operator-1.3.1-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-ppc64le digest=sha256:30482e638d2d036903f3c5c3ec8e0e18373461942bc4c4b1d1b255eade1e2647 arch=ppc64le
Saving artifact operator-1.3.1-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.1-s390x digest=sha256:c266068575c575183b9ba4101d43b76fc7fde2c54ad6769b01172f7123acf6a6 arch=s390x

Saving artifact bundle-1.3.1 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.1 digest=sha256:3c1dc0557f25e38dec0c8e43cd71c0d00242293a6e84e49eccdaed07d7b02155

Saving artifact catalog-1.3.1 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1 digest=sha256:f935af6f90d7db073fc950464427c8601f4dc0acd4cfde474b42701ff2c53881
Saving artifact catalog-1.3.1-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-amd64 digest=sha256:49a00b7cbf8120f4b571b92ab3d8940985903c8fd76bd61a44f9d321ee2662f6 arch=amd64
Saving artifact catalog-1.3.1-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-ppc64le digest=sha256:b07a936d1b648f467247e67f0de765a6e04f52f9978e4b12c9cf50e1f6c5e7f8 arch=ppc64le
Saving artifact catalog-1.3.1-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.1-s390x digest=sha256:1ca08573a4292909e3b73f78944606788d1e41059185100d8bc27d764f8d8ebf arch=s390x

Saving artifact operator-1.3.1 type=manifest name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:d735c2ceae5945a0f20adcbcb04e55472d2520b6d1abb6d3049c8521234d3b7a
Saving artifact sample-1.3.1 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:190e2ed4b9f728fe760393a455eba5002a82f84652a4e9221dc53fd856ecc0a5 arch=amd64
Saving artifact sample-1.3.1 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:f8e38bb5ee4044b56f4f99bacc33c8b18d4ea8fddafa2c6ce8376bcaa8801b34 arch=ppc64le
Saving artifact sample-1.3.1 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:09d3070230f8331a069762044b00188e8b50c1255c4dce87cff00c4d74f7b58e arch=s390x
```

**Comment by leochr** [comment]
@kabicin Please update the CASE with the above image details from the WLO 1.3.1 release build. The getting-started sample image was also updated. Thank you.

**Comment by kabicin** [comment]
I've updated the CASE with the new image digests

**Comment by leochr** [comment]
@mingcyu The release process for WLO 1.3.1 has been completed. The Certification entry can be approved and published.

**Comment by leochr** [comment]
Closing as complete
