### ISSUE TITLE
Release WLO 1.3.2

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#627]
- [ ] Schedule any UFOs for new Features
- [x] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline)
- [x] Scans(Done for each release build): 
  - [ ] VA
  - [x] Twistlock
  - [x] SonarQube
  - [x] Mend
  - [x] Aquascan
- [x] Linter
- [ ] Certification Related Work Items
- [x] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [x] Identify SVT Testing that is needed
- [x] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [x] Update websphereliberty-app-crd.yaml if necessary
  - [x] Creating the Pre-Release: 
  - [x] Kick off build using the pre-release tags
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Kirby / Melissa (Out of containerized step)
- [x] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [x] Open Source Clearance
  - [ ] Provide customer installable code to PTC for scan
  - [x] Run the scan to determine the package differences ourselves and provide results to PM (Marylin / Cass)
- [x] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [x] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [x] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Mary ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [ ] Update webspehreliberty-app-crd.yaml to point to GA release image
- [x] Push the images to the production repo (Using CD Instructions)
- [ ] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [x] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [x] Publish assessment (CASE will get published when this happens)
- [ ] Are any patentable ideas delivered with this release?

**Comment by leochr** [comment]
@kabicin WLO 1.3.2 pre-release image details (from WLO build [2075](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/8cb93ec0-dc91-485e-bcc3-bc9317c21c14/build-containerize/run-stage?env_id=ibm:yp:us-south). Please update the CASE to produce the tgz file for SVT testing. Thank you.

```
**** Saving Artifacts ****
Saving artifact operator-1.3.2-rc.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.2-rc.2 digest=sha256:2b7067d83838b739acd8718da5602709578aad1d5aba680848e6be9e0cd46f5d
Saving artifact operator-1.3.2-rc.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.2-rc.2-amd64 digest=sha256:6236929266e3d5873de4292d7bee6c6af6d19addd7c77693f697cd85a2cb99f2 arch=amd64
Saving artifact operator-1.3.2-rc.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.2-rc.2-ppc64le digest=sha256:c5168c53357ba1330178410aabb8c12f51d8c63094f921df15b4c63d8179aa8b arch=ppc64le
Saving artifact operator-1.3.2-rc.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.2-rc.2-s390x digest=sha256:01ea0881850bf620f64e9348c7738b070237cb48eb4600a1dec9d62619fe46d9 arch=s390x
Saving artifact bundle-1.3.2-rc.2 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.2-rc.2 digest=sha256:3b93f19292a3daf3207445b3ac2a8daddb23e4fc0e5b95a00250de8cb9e1b40b
Saving artifact catalog-1.3.2-rc.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.2-rc.2 digest=sha256:b1960fc903dbaa90c2c4898b75c3db09de32648135742455f4b89ff90f252855
Saving artifact catalog-1.3.2-rc.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.2-rc.2-amd64 digest=sha256:cf600522675bdbf22206a1e3ba9c81ce22e8c10a6b322cab00386babf427bf8e arch=amd64
Saving artifact catalog-1.3.2-rc.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.2-rc.2-ppc64le digest=sha256:9890ae00af8a4a4680b7c44ddbd8a4a8ff068f50d4df410fafa888a592720a7b arch=ppc64le
Saving artifact catalog-1.3.2-rc.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.2-rc.2-s390x digest=sha256:42040fa3f33542f38aa44612075d3a1c80adffb397741099625d987e0db3dfd9 arch=s390x
CSV FILE: bundle/manifests/ibm-websphere-liberty.clusterserviceversion.yaml
Saving artifact sample-1.3.2-rc.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:445f246ae46230dd2a800a792f2833f8ff531a72f0b2c72ae8046114285fe8e7 arch=amd64
Saving artifact sample-1.3.2-rc.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:58649da420d1b2fafb477afc856e365bf691e1670b748bb734902d025bf53117 arch=ppc64le
Saving artifact sample-1.3.2-rc.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:0e205f8e814285b92c18cb14956b5a022646e74f4f198cfcef60c61b65ec3eac arch=s390x
```

**Comment by leochr** [comment]
@dtadcox Please run the package difference analysis between these 2 releases/tags: [1.3.0](https://github.com/WASdev/websphere-liberty-operator/releases/tag/1.3.0) and [1.3.2-rc.2](https://github.com/WASdev/websphere-liberty-operator/releases/tag/1.3.2-rc.2) and include the results here. Thank you

**Comment by dtadcox** [comment]
[Report_1.3.0-1.3.2-rc.2.txt](https://github.com/WASdev/websphere-liberty-operator/files/15222086/Report_1.3.0-1.3.2-rc.2.txt)

**Comment by dtadcox** [comment]
[Report_1.3.0-1.3.2-rc.2.txt](https://github.com/WASdev/websphere-liberty-operator/files/15225561/Report_1.3.0-1.3.2-rc.2.txt) Updated

**Comment by leochr** [comment]
@kabicin WLO 1.3.2 release image details (from [WLO CI build #2124](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/f88a515e-263e-4ac5-894c-23f61febd97b/build-containerize/run-stage?env_id=ibm:yp:us-south) and [WLO CD build #77](https://cloud.ibm.com/devops/pipelines/tekton/e77b8f53-3bb3-471f-bea8-8396bfe6b5be/runs/afe13319-bb5b-4bb3-a570-9b72ac2b0b8c/prod-deployment/run-stage?env_id=ibm:yp:us-south)). Please update the CASE. Thank you.

```
**** Saving Artifacts ****
Saving artifact operator-1.3.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.2 digest=sha256:c121b246d3257601f9ea97728034d93544c3b69ace2136f75f56b1382e70791a
Saving artifact operator-1.3.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.2-amd64 digest=sha256:bfc787fa5a3ff724100ca29df68e1f324dc2ba585d834a5437d4010302d77ba8 arch=amd64
Saving artifact operator-1.3.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.2-ppc64le digest=sha256:3b73119d1cc980ce947c9c8fa8c8276e6e452b19ba60389081dc5f1fa819b882 arch=ppc64le
Saving artifact operator-1.3.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.2-s390x digest=sha256:f8abe72135554863a2b26e688262cf3d67e273e11f3a829ec5c5276e90947702 arch=s390x

Saving artifact bundle-1.3.2 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.2 digest=sha256:fb26d5e86a726e4ba4420d49a603fea1f1cb9c5f68163354bb546efd705df274

Saving artifact catalog-1.3.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.2 digest=sha256:3413030587e4312228d9a089c7b1f8900989838945df8cfd9ca5799b0bd8352a
Saving artifact catalog-1.3.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.2-amd64 digest=sha256:20e1e1477716712842f75d1a4686e4691f4d37014853d2bfe486bd71a7078a5f arch=amd64
Saving artifact catalog-1.3.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.2-ppc64le digest=sha256:e9176e0150ea5adb8a095e62fa876a3c14c0cfa8788fb5f124f7230abb3be668 arch=ppc64le
Saving artifact catalog-1.3.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.2-s390x digest=sha256:bb0943891b6b075c01d7329714f9b828f1490254ffe545796d44743045e9e4d0 arch=s390x

Saving artifact sample-1.3.2-rc.2 type=manifest name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:fd04ce5a5870387a379b54da5c47d0338c5f4a1254611d2418f1f959d018ba7e
Saving artifact sample-1.3.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:70e018a9e6cb0e32d0516b961e2991c4fdb7c39d029d7c8c2f8231d53806e501 arch=amd64
Saving artifact sample-1.3.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:b1fe6ad58d0e8688c522067ad81894df07879a7d46b316028864749cedd095da arch=ppc64le
Saving artifact sample-1.3.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:afe68c8d34491c20425ea4b4d8fb6888dde77ec22ec650f25b45f4e4ae972c10 arch=s390x
```
