### ISSUE TITLE
Release WLO 1.3.3

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#659]
- [ ] Schedule any UFOs for new Features
- [x] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline)
- [ ] Scans(Done for each release build): 
  - [ ] VA
  - [x] Twistlock
  - [x] SonarQube
  - [x] Mend
  - [x] Aquascan
- [x] Linter
- [ ] Certification Related Work Items
- [x] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [x] Identify SVT Testing that is needed
- [x] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [x] Update websphereliberty-app-crd.yaml if necessary
  - [x] Creating the Pre-Release: 
  - [x] Kick off build using the pre-release tags
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Kirby (Out of containerized step)
- [x] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [x] Provide customer installable code to PTC for Open Source Clearance
- [ ] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [x] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [x] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Kirby ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [ ] Update webspehreliberty-app-crd.yaml to point to GA release image
- [x] Push the images to the production repo (Using CD Instructions)
- [ ] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [x] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [x] Publish assessment (CASE will get published when this happens)
- [ ] Are any patentable ideas delivered with this release?

**Comment by leochr** [comment]
@kabicin WLO 1.3.3 pre-release image details (from WLO build [2200](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/f3aedcd0-89e9-4132-9ff3-b1983553378b/build-containerize/run-stage?env_id=ibm:yp:us-south). Please update the CASE to produce the tgz file for SVT testing. Thank you.

```
**** Saving Artifacts ****
Saving artifact operator-1.3.3-rc.1 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-rc.1 digest=sha256:0c298511d8bab5d22858a4f56c7ca8e34886950597c21073a9860ddf7475032a
Saving artifact operator-1.3.3-rc.1-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-rc.1-amd64 digest=sha256:5cabcb5e5b8d01809630b82020d13b214160ca1c580069ad83b8ee6fca57d0e0 arch=amd64
Saving artifact operator-1.3.3-rc.1-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-rc.1-ppc64le digest=sha256:816435561c59753b5fea8ed39b6323905bf7d2962ea5308aa10fc4273c86acdd arch=ppc64le
Saving artifact operator-1.3.3-rc.1-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-rc.1-s390x digest=sha256:197da346dc7d4caf81a24d9d70c27fd9486040c1be6aabb6b6d548b6b9ca9c66 arch=s390x

Saving artifact bundle-1.3.3-rc.1 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.3-rc.1 digest=sha256:0fe8159b29503f23e67b8241a9a30905e0b1addc1139c10b56bf0d66742c9ceb

Saving artifact catalog-1.3.3-rc.1 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-rc.1 digest=sha256:a71eb9681020e5c77744be4d1d87db55013e9eee844eb33a403274482ba0061f
Saving artifact catalog-1.3.3-rc.1-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-rc.1-amd64 digest=sha256:4b59cc8e5b4734e8f4a78e41699b85b934eda723b14ef0e67a60f83c91c148b1 arch=amd64
Saving artifact catalog-1.3.3-rc.1-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-rc.1-ppc64le digest=sha256:5ccbaaa0d199c0ed7e62dc98c91fc98ac294b8ee91cb061926576dd5924a110b arch=ppc64le
Saving artifact catalog-1.3.3-rc.1-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-rc.1-s390x digest=sha256:138fe4b47e806e57c88a9cf7a31538a9c21577794ea281a530085a34a5df2932 arch=s390x

Saving artifact latest type=manifest [name=stg.icr.io/cp/olc-sample/open-liberty/samples/getting-started:latest](http://name=stg.icr.io/cp/olc-sample/open-liberty/samples/getting-started:latest) digest=sha256:e74e4c7bcc6999d704bafbb92bf78a6c776953401fd37f3597e3f4ebca0c3952
Saving artifact latest-amd64 type=image [name=stg.icr.io/cp/olc-sample/open-liberty/samples/getting-started:latest-amd64](http://name=stg.icr.io/cp/olc-sample/open-liberty/samples/getting-started:latest-amd64) digest=sha256:f5a903538821034d576239b06cc67f14f4b0507b00e51a876a3d82b2d8329534 arch=amd64
Saving artifact latest-ppc64le type=image [name=stg.icr.io/cp/olc-sample/open-liberty/samples/getting-started:latest-ppc64le](http://name=stg.icr.io/cp/olc-sample/open-liberty/samples/getting-started:latest-ppc64le) digest=sha256:8e63c87b1b739801bdfe5dc130c315987baec3c7befde127b1b74fe70aa84093 arch=ppc64le
Saving artifact latest-s390x type=image [name=stg.icr.io/cp/olc-sample/open-liberty/samples/getting-started:latest-s390x](http://name=stg.icr.io/cp/olc-sample/open-liberty/samples/getting-started:latest-s390x) digest=sha256:b3747b4d89b18cccc8f3a78196504f92f0b9804f425bf1123420bdd6e301faa1 arch=s390x
```

**Comment by leochr** [comment]
@kabicin pre-release Operator images from 1.3.3-rc.2. Please update the CASE with these. Thank you.

```
Saving artifact operator-1.3.3-rc.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-rc.2 digest=sha256:112730bdda560d7e406e3a7df87e4f73c2d717879434acec740423a1f3201e5f
Saving artifact operator-1.3.3-rc.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-rc.2-amd64 digest=sha256:0a26217455955186676f3db4e4148c78bdef93058c9154da3c2413601d1273c0 arch=amd64
Saving artifact operator-1.3.3-rc.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-rc.2-ppc64le digest=sha256:b8f5af76fcfdbf329e11e566152101dccc3c11b0825f44b2861469530d80a4f9 arch=ppc64le
Saving artifact operator-1.3.3-rc.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-rc.2-s390x digest=sha256:090f1b07a94dcdcace30f71ce27f14b0b802ffc76b6fbdc94c2fda4cca55b526 arch=s390x

Saving artifact bundle-1.3.3-rc.2 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.3-rc.2 digest=sha256:7fa85519e973df7a38f28f46ca58202a6ace75de1d8918e1f1aa6ecfbe1e839e

Saving artifact catalog-1.3.3-rc.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-rc.2 digest=sha256:bc87dad96375795fe4aa90068cc60d51d3f599ff9bb589f1cf268998c9b0b75e
Saving artifact catalog-1.3.3-rc.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-rc.2-amd64 digest=sha256:667cbc0f9ed53777fb5df9762c466f488680556bd0a6cf9d9aa7ddc1a768f447 arch=amd64
Saving artifact catalog-1.3.3-rc.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-rc.2-ppc64le digest=sha256:3825a3c1ac35bf72a5a51b69f9f660198e53a5f5c7f2ca7dcf6547f9f2b39f18 arch=ppc64le
Saving artifact catalog-1.3.3-rc.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-rc.2-s390x digest=sha256:813b478535717f12d8d29f04892bef07dd95171071bce6c62e75a8a8675ef54e arch=s390x
```
The getting-started sample image hasn't changed

**Comment by leochr** [comment]
@dtadcox Please run the Open Source license tool to generate the json file for ServiceNow using the following pre-release driver for WLO 1.3.3. Thank you
[1.3.3-rc.2](https://github.com/WASdev/websphere-liberty-operator/releases/tag/1.3.3-rc.2)

**Comment by leochr** [comment]
Notices file was updated (PR https://github.com/WASdev/websphere-liberty-operator/pull/666/files for reference)

**Comment by leochr** [comment]
@kabicin Image details from the 1.3.3 GA build ([WLO CI 2212](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/b3da60db-b1e1-4b3c-9e9f-0b59d6caecd4/build-containerize/run-stage?env_id=ibm:yp:us-south)). Please update the CASE:

```
Saving artifact operator-1.3.3 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3 digest=sha256:655eeead9f31a8e2980642bd0e54d6a46446051d0333a9ab46f0cc0f2ee43283
Saving artifact operator-1.3.3-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-amd64 digest=sha256:2b1382332e8a573adddef6201cb864cf0d537f3cc8cea592f898005f3d83bb65 arch=amd64
Saving artifact operator-1.3.3-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-ppc64le digest=sha256:4643f425f728dedafa2e23a2a0b7dd76287a10c8e84fd888a33eeb5a98b94e8e arch=ppc64le
Saving artifact operator-1.3.3-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.3.3-s390x digest=sha256:ae30549cbe8a7a440f0521c5b0508044875d51dd529c45b036cc4cb1f72f75f2 arch=s390x

Saving artifact bundle-1.3.3 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.3.3 digest=sha256:f71ced9b0e7f3b27645bd4b53b46e14c461a57b17dcfd83488332d979d56d448

Saving artifact catalog-1.3.3 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3 digest=sha256:1fa14994fc0ac0cbf19742ea8d828dde81a53d7889e9c72b0fb1ecc805856855
Saving artifact catalog-1.3.3-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-amd64 digest=sha256:d71c3a83f908b79ce31308e696d65d4d52564a19846a38573b4d67cc16c7157d arch=amd64
Saving artifact catalog-1.3.3-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-ppc64le digest=sha256:1a60ec59ae19edc8852e7f46d71274dbcde149e1c816f700ed19617533e89203 arch=ppc64le
Saving artifact catalog-1.3.3-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.3.3-s390x digest=sha256:4fa7b42db22fe38ed34072abaf4d9d33dd24e437648c1309e01cd75a5bd15e4f arch=s390x

Saving artifact latest type=manifest name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:422a7a00edc338497c0a91890b09204b8505ef0e377bb9b5944ace0102055e91
Saving artifact latest-amd64 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:feea04f186c83e82a30291769197c1785b0039afe62e73c055c336c12b7ae36b arch=amd64
Saving artifact latest-ppc64le type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:2dabce9fd5c2de70a0f663cd8fd3fc88fdb47931a4b7e1dd49a70a88ba254377 arch=ppc64le
Saving artifact latest-s390x type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:83715c38bbd10abe97f6aa05324afdaecc75556983ddcf55213a42c61787379c arch=s390x
```

**Comment by leochr** [comment]
Images were published to the production registry (icr.io) on Friday by [WLO CD 78](https://cloud.ibm.com/devops/pipelines/tekton/e77b8f53-3bb3-471f-bea8-8396bfe6b5be/runs/c58b427b-9a8d-47b3-89e2-3d414cd683df/prod-start/start?env_id=ibm:yp:us-south)

**Comment by leochr** [comment]
Validated that the latest CASE tgz file includes the digests of 1.3.3 GA images. Proceeding to add approval to the CASE PR to publish 1.3.3 : https://github.ibm.com/CloudPakEngineering/cloud-pak/pull/1436

**Comment by leochr** [comment]
Closing as completed
