### ISSUE TITLE
Release WLO 1.4.0

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#676]
- [ ] Schedule any UFOs for new Features
- [ ] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline)
- [ ] Scans(Done for each release build): 
  - [ ] VA
  - [ ] Twistlock
  - [ ] SonarQube
  - [ ] Mend
  - [ ] Aquascan
- [ ] Linter
- [ ] Certification Related Work Items
- [ ] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [ ] Identify SVT Testing that is needed
- [ ] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [ ] Update websphereliberty-app-crd.yaml if necessary
  - [ ] Creating the Pre-Release: 
  - [ ] Kick off build using the pre-release tags
  - [ ] Set the flag to run e2e in all modes
  - [ ] Check e2e results
  - [ ] Provide image details to Mary (Out of containerized step)
- [ ] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [ ] Provide customer installable code to PTC for Open Source Clearance
- [ ] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [ ] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [ ] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [ ] Check e2e results
  - [ ] Provide image details to Mary ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [ ] Update webspehreliberty-app-crd.yaml to point to GA release image
- [ ] Push the images to the production repo (Using CD Instructions)
- [ ] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [ ] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [ ] Publish assessment (CASE will get published when this happens)
- [ ] Are any patentable ideas delivered with this release?

**Comment by leochr** [comment]
Images from 1.4.0-rc.2 ([WLO CI 2301](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/099ea640-f691-4e61-bec4-787c07603491/build-containerize/run-stage?env_id=ibm:yp:us-south)):

```
**** Saving Artifacts ****
Saving artifact operator-1.4.0-rc.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.0-rc.2 digest=sha256:aad1b286b66294482e84c77107499643e8df6de69a2e22de7213be3a8658d9d7
Saving artifact operator-1.4.0-rc.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.0-rc.2-amd64 digest=sha256:ac3bb0f33c25cba044ecf801db46e2d95c10d4c85d8bcdc935636f00262e55cf arch=amd64
Saving artifact operator-1.4.0-rc.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.0-rc.2-ppc64le digest=sha256:496e66a7aae6a2495428a6ecfdd3a4a9f546285e0a0c9c890c5600083ae5c082 arch=ppc64le
Saving artifact operator-1.4.0-rc.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.0-rc.2-s390x digest=sha256:5a5243946e09651c46f53741c6b748606463143a138c2e85b846dd5a91e26ec3 arch=s390x

Saving artifact bundle-1.4.0-rc.2 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.4.0-rc.2 digest=sha256:8ad54453afa61d1cdec3816d980a8380d5a6225661473b4509161cf4d9c06199

Saving artifact catalog-1.4.0-rc.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.0-rc.2 digest=sha256:7f6de62aaeb4942b0c8291ed9770aee392325fa2b22edcc6b96b2688174b813d
Saving artifact catalog-1.4.0-rc.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.0-rc.2-amd64 digest=sha256:27c16799c68911d695a0f1c98edd9947ea30f29bd1769400ff77cdece924fca9 arch=amd64
Saving artifact catalog-1.4.0-rc.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.0-rc.2-ppc64le digest=sha256:5239ed9a92b58e34539ab977d4633fc09e9cc7069f5ffaff60742296637e9c7d arch=ppc64le
Saving artifact catalog-1.4.0-rc.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.0-rc.2-s390x digest=sha256:41d51f3c12371d506cfbf4331ad8aa0c55551e7cdecb23ec65a608e2268a7d7e arch=s390x

Saving artifact sample-1.4.0-rc.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:a4c39872f2a5ecb01ac8dc366d338868a7472574aa6e700f34feda80b826451f arch=amd64
Saving artifact sample-1.4.0-rc.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:da343f736e9ef51c4fc2f4f1ae9f54ea82adb430f4cbe803de72c94d32ec5a2a arch=ppc64le
Saving artifact sample-1.4.0-rc.2 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:5657ed1174e0c3325a9ae75db8da5037ea2fdc84e5883a42edd8704665218ac1 arch=s390x
```

**Comment by leochr** [comment]
@kabicin Please update the CASE to use the above images and channel `v1.4`. Thank you

**Comment by kabicin** [comment]
Updated [liberty-case-bundle](https://github.ibm.com/websphere/liberty-case-bundle/pull/91) and [CASE](https://github.ibm.com/CloudPakEngineering/cloud-pak/pull/1742) for pre-release

**Comment by leochr** [comment]
@kabicin Please update the CASE to use the following images from 1.4.0-rc.3 ([WLO CI 2312](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/188e07e8-1fdd-40f7-a7f3-306f03c63ef9/build-containerize/run-stage?env_id=ibm:yp:us-south)):

```
**** Saving Artifacts ****
Saving artifact operator-1.4.0-rc.3 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.0-rc.3 digest=sha256:e6f7a4c981baaab20d395f9c035d2e74ef2ecf9893b7b204b104938a619555c3
Saving artifact operator-1.4.0-rc.3-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.0-rc.3-amd64 digest=sha256:371f060a77c05b49f0c67443b6003287f2fcefbd79d968f367611657519156a0 arch=amd64
Saving artifact operator-1.4.0-rc.3-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.0-rc.3-ppc64le digest=sha256:33b01e2d347ecfb0fe105cffe5b676de93a4ca448db5106ecf43661c5bba8b9e arch=ppc64le
Saving artifact operator-1.4.0-rc.3-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.0-rc.3-s390x digest=sha256:f8458cd1de8f0eceba2962adc2b52d01a7b2ec7d598a6fdc61402023e2cbe5d8 arch=s390x

Saving artifact bundle-1.4.0-rc.3 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.4.0-rc.3 digest=sha256:226b71e9c63fe4daecff839e3654ad4a84c18d97c4f316d62ff78a85813bcaf2

Saving artifact catalog-1.4.0-rc.3 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.0-rc.3 digest=sha256:071a44606c2beea7b842685472031ffd9923ef042fc5fef7bbd5c53b28060fb8
Saving artifact catalog-1.4.0-rc.3-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.0-rc.3-amd64 digest=sha256:15b30d382de95904a8d25790f66026e6213951116c721cc78bd2bc6342e86e99 arch=amd64
Saving artifact catalog-1.4.0-rc.3-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.0-rc.3-ppc64le digest=sha256:14ea99cdb40078d7f66d3f84275dde8cf914fed65f63dd5e1617d69a105be7bd arch=ppc64le
Saving artifact catalog-1.4.0-rc.3-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.0-rc.3-s390x digest=sha256:4935438ebd76f28d50d3eea58f02776d4e3e042972631f28e12e785b2d372d1c arch=s390x

Saving artifact latest type=manifest name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:91589e8e215d416595b045c739724385ffe34364df06d36794dca0d6964053e7
Saving artifact latest-amd64 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:a4c39872f2a5ecb01ac8dc366d338868a7472574aa6e700f34feda80b826451f arch=amd64
Saving artifact latest-ppc64le type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:da343f736e9ef51c4fc2f4f1ae9f54ea82adb430f4cbe803de72c94d32ec5a2a arch=ppc64le
Saving artifact latest-s390x type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:5657ed1174e0c3325a9ae75db8da5037ea2fdc84e5883a42edd8704665218ac1 arch=s390x
```

**Comment by kabicin** [comment]
Updated [liberty-case-bundle](https://github.ibm.com/websphere/liberty-case-bundle/pull/92) and triggered update on [CASE](https://github.ibm.com/CloudPakEngineering/cloud-pak/pull/1742#issuecomment-89985058)

**Comment by leochr** [comment]
GA image details ([WLO CI 2335](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/2e532bc4-c35a-4004-8369-27ba6983dfec/build-containerize/run-stage?env_id=ibm:yp:us-south) and [WLO CD 79](https://cloud.ibm.com/devops/pipelines/tekton/e77b8f53-3bb3-471f-bea8-8396bfe6b5be/runs/74ca08e9-024c-43f6-b065-b13cdc64a3c3/prod-deployment/run-stage?env_id=ibm:yp:us-south)). Changed staging repo reference to production. 

@halim-lee / @kabicin please update the CASE. Thank you

```
Saving artifact operator-1.4.0 type=manifest name=icr.io/cpopen/websphere-liberty-operator:1.4.0 digest=sha256:acb7fa61362c05ba5a49466777255a056dbb53868906a74544cccdc3414fb055
Saving artifact operator-1.4.0-amd64 type=image name=icr.io/cpopen/websphere-liberty-operator:1.4.0-amd64 digest=sha256:29d92762c2887fad63f459c4655d719573450b5173dda136a02374bf818b6889 arch=amd64
Saving artifact operator-1.4.0-ppc64le type=image name=icr.io/cpopen/websphere-liberty-operator:1.4.0-ppc64le digest=sha256:03aee6d91d99ddf583eb914356e77fefc9fc3b3d3191d9c37e10798ab4edf96a arch=ppc64le
Saving artifact operator-1.4.0-s390x type=image name=icr.io/cpopen/websphere-liberty-operator:1.4.0-s390x digest=sha256:8b1ccf3f1ce782b94ee2c8cd678052dc96279222f011dee059b5bb40a05a287a arch=s390x

Saving artifact bundle-1.4.0 name=icr.io/cpopen/websphere-liberty-operator-bundle:1.4.0 digest=sha256:28763357f05ba5451f629987367d78d2d6831191453bf6582f6bd68bec546d14

Saving artifact catalog-1.4.0 type=manifest name=icr.io/cpopen/websphere-liberty-operator-catalog:1.4.0 digest=sha256:16a25932a4a2b0b529f9110537daee9e84aacb5fae8bb5c94a44341203597461
Saving artifact catalog-1.4.0-amd64 type=image name=icr.io/cpopen/websphere-liberty-operator-catalog:1.4.0-amd64 digest=sha256:76e63dd35ea1b8ff4e9b83bdc557eee017e36354ba4db6356958b03c89a0b4ab arch=amd64
Saving artifact catalog-1.4.0-ppc64le type=image name=icr.io/cpopen/websphere-liberty-operator-catalog:1.4.0-ppc64le digest=sha256:f559a198954fd782cf55e38111cba34ef7c63f89a2ced6981089c2d46d220877 arch=ppc64le
Saving artifact catalog-1.4.0-s390x type=image name=icr.io/cpopen/websphere-liberty-operator-catalog:1.4.0-s390x digest=sha256:40924d88927f8e92f83a2f8ac988472c2421f0f6b7a6c55d89f175a241f22e87 arch=s390x


Saving artifact latest type=manifest name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:3999aa86f788e601d305896e48a043a91861cdbf71951a1959887151390b3650
Saving artifact latest-amd64 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:ae5e4d90332a9679e4190f2ac9cba2a4e67f2c5aa73741a9c9526a1479a5da1e arch=amd64
Saving artifact latest-ppc64le type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:0116883b9248b4b1f14bc85d39e44fa2cff27ab120278d72f4002d572887e48f arch=ppc64le
Saving artifact latest-s390x type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:f4a60a119ce02e8f3ff8138782b21b7a73aed1cef5c32a1f122d14e9cc3f3d35 arch=s390x
```

**Comment by leochr** [comment]
Validated that the latest CASE tgz file includes the digests of 1.4.0 GA images. Added approval to the CASE PR to publish 1.4.0 : https://github.ibm.com/CloudPakEngineering/cloud-pak/pull/1742
