### ISSUE TITLE
Release WLO 1.4.1

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#711]
- [ ] Schedule any UFOs for new Features
- [x] Enable and verify the upgrade support for this release version (Using catalog image produced by One Pipeline)
- [x] Scans(Done for each release build): 
  - [ ] VA
  - [x] Twistlock
  - [ ] SonarQube
  - [x] Mend
  - [x] Aquascan
- [x] Linter
- [ ] Certification Related Work Items
- [x] Update Liberty Sample app ([here](https://github.com/WASdev/websphere-liberty-operator/blob/1437996159871dd52d23372ffa08ff1e7eec3010/config/samples/liberty.websphere.ibm.com_v1_webspherelibertyapplications.yaml#L11)). (To use as part of early verification)
- [x] Identify SVT Testing that is needed
- [x] Create a total of 2 pre-release drivers in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
- [ ] Update websphereliberty-app-crd.yaml if necessary
  - [x] Creating the Pre-Release: 
  - [x] Kick off build using the pre-release tags
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Kirby (Out of containerized step)
- [x] Update Liberty Sample Version (Done as close to feature complete as possible) 
- [x] Provide customer installable code to PTC for Open Source Clearance
- [x] Preparing for GM release in GH (Done after all changes are in and SVT has completed)
  - [x] Create a GM Release in GH following these [instructions](https://github.ibm.com/websphere/operators/wiki/Creating-Operator-Releases-and-Tagging-them-for-use-with-Case#for-release-candidates-for-10x-and-above)
  - [x] Kick off build using the GM release tag. **Important** Make sure that "Release" is set to true. It is "false" by default which is fine for pre-release activity
  - [ ] Set the flag to run e2e in all modes
  - [x] Check e2e results
  - [x] Provide image details to Kirby ([Out of containerized step](https://github.ibm.com/websphere/operators/wiki/Running-the-CD-Pipeline-for-the-GM-Operator-Release))
  - [x] Update webspehreliberty-app-crd.yaml to point to GA release image
- [x] Push the images to the production repo (Using CD Instructions)
- [ ] Certification: create a new cert item in the tool as well as the GH repo, answer any questions
- [x] Work with ID to refresh upgrade instructions (use WebSphere Automation Operator docs)
- [x] Publish assessment (CASE will get published when this happens)
- [ ] Are any patentable ideas delivered with this release?

**Comment by leochr** [comment]
@kabicin Please update the CASE with the following pre-release candidate:

```
Saving artifact operator-1.4.1-rc.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.1-rc.2 digest=sha256:896a4dcaeb4cc02e4b5f29fc090e1de77309ca7447761ecf31ce92b2eb18b2bb
Saving artifact operator-1.4.1-rc.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.1-rc.2-amd64 digest=sha256:b4e68571f2bd509f7437ad2e0fce833c4a45e1365040776c116f9ca70623228d arch=amd64
Saving artifact operator-1.4.1-rc.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.1-rc.2-ppc64le digest=sha256:fb25061983dd6dc2b878364cf84a9459018849aca2b719743ad80ce62a27cba3 arch=ppc64le
Saving artifact operator-1.4.1-rc.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator:1.4.1-rc.2-s390x digest=sha256:fcf198f1708c07b83db08a915af3850d94514c51f2a7447dca3ed29e0ed946f6 arch=s390x

Saving artifact bundle-1.4.1-rc.2 name=cp.stg.icr.io/cp/websphere-liberty-operator-bundle:1.4.1-rc.2 digest=sha256:8a9d054a7a5301c3b5801554b5678b7eb42fc9915b7db9d911845da069256158

Saving artifact catalog-1.4.1-rc.2 type=manifest name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.1-rc.2 digest=sha256:09e148fc95c489450a2fcc1252ce99b4f1d7acb4216d44f5a1fc917ca9c79943
Saving artifact catalog-1.4.1-rc.2-amd64 type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.1-rc.2-amd64 digest=sha256:e5320b77f734726553855840ab18be59ec1f10114266ee262bf0854f8c68393c arch=amd64
Saving artifact catalog-1.4.1-rc.2-ppc64le type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.1-rc.2-ppc64le digest=sha256:582045fcf95befb88800a45a013f6a10d548ab32cb60c7bcb3af2bd2ecf8b053 arch=ppc64le
Saving artifact catalog-1.4.1-rc.2-s390x type=image name=cp.stg.icr.io/cp/websphere-liberty-operator-catalog:1.4.1-rc.2-s390x digest=sha256:c739d091ffd53c1ae11c881f0bac4d79c3fffeabe89982ad700abb514b2ad31d arch=s390x

Saving artifact latest type=manifest name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:1ac4699f934128ed62da43b3720120d469e930458355152e547a574bb7b70c07
Saving artifact latest-amd64 type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:596d0dfa9637858c1e473e2173b8a478f8a110daa3099f722f83bbdb97477c7e arch=amd64
Saving artifact latest-ppc64le type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:272ff37ab2fff29430294c767e88335f3389b036b83aaee88b31b6ae1332cfae arch=ppc64le
Saving artifact latest-s390x type=image name=icr.io/appcafe/open-liberty/samples/getting-started digest=sha256:8ea536cbd8b7ab7a173a436f86fb133ed6de273e7616c474177026421a611ae5 arch=s390x
```

**Comment by kabicin** [comment]
Created PRs
https://github.ibm.com/websphere/liberty-case-bundle/pull/94
https://github.ibm.com/CloudPakEngineering/cloud-pak/pull/2330

**Comment by leochr** [comment]
Thank you @kabicin . Merged [PR 94](https://github.ibm.com/websphere/liberty-case-bundle/pull/94).

**Comment by leochr** [comment]
@idlewis Please use the 1.4.1 CASE in the staging repo to test and validate in an Airgap environment:
https://github.ibm.com/IBMPrivateCloud/cloud-pak/tree/master/repo/case/ibm-websphere-liberty/1.4.1

**Comment by leochr** [comment]
@idlewis tested the above CASE from the staging registry and validated that it works fine. All functional tests passed.

**Comment by kabicin** [comment]
@leochr added your review on https://github.ibm.com/websphere/liberty-case-bundle/pull/95/files for the 1.4.1 changes.

**Comment by leochr** [comment]
@kabicin Thank you. Approved PR.

Images are now published to icr.io production registry (by [WLO CD 80](https://cloud.ibm.com/devops/pipelines/tekton/e77b8f53-3bb3-471f-bea8-8396bfe6b5be/runs/6786e2ef-aa17-417b-81d9-2374fb7efaa5/prod-acceptance-tests/run-stage?env_id=ibm:yp:us-south)).

**Comment by leochr** [comment]
Approved https://github.ibm.com/CloudPakEngineering/cloud-pak/pull/2330. The release is underway.

**Comment by leochr** [comment]
WLO 1.4.1 was released yesterday (Dec 9, 2024). Closing as completed.
